# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVlmkGQOGBmej8BHkR1x0KzMk8mmu9xP

Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

"""Load Dataset"""

df = pd.read_csv("/content/creditcard.csv")

"""Data Cleaning"""

df = df.drop_duplicates()
# Drop rows with NaN values in 'Time', 'Amount', or 'Class' as they are used in the model
df.dropna(subset=["Time", "Amount", "Class"], inplace=True)
print(df.isnull().sum())

"""Descriptive Statistics"""

print(df["Class"].value_counts())
print(df["Amount"].describe())

"""Fraud Analysis"""

fraud = df[df["Class"] == 1]
normal = df[df["Class"] == 0]

print("Fraud Transactions:", len(fraud))
print("Normal Transactions:", len(normal))

"""Visualization

Fraud Distribution
"""

sns.countplot(x="Class", data=df)
plt.title("Fraud Distribution")
plt.show()

"""Transaction Amount Distribution"""

plt.hist(df["Amount"], bins=30)
plt.title("Transaction Amount")
plt.show()

""" Correlation Heatmap"""

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

"""Risk Analysis"""

def risk(amount):
    if amount < 100:
        return "Low Risk"
    elif amount < 1000:
        return "Medium Risk"
    else:
        return "High Risk"

df["Risk"] = df["Amount"].apply(risk)

print(df[["Amount", "Risk"]].head())

"""Linear Regression Model

Independent Variables
"""

X = df[["Time", "Amount"]]

"""Dependent Variable"""

y = df["Class"]

"""Split Data"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

""" Prediction

"""

y_pred = model.predict(X_test)

"""Model Evaluation

"""

print("R2 Score:", r2_score(y_test, y_pred))

""" Conclusion

"""

print("\nFraud detection analysis completed successfully.")

